### ISSUE TITLE
Cannot replicate the tutorial

### ISSUE THREAD

**Issue by dpolimeni** [ArjanCodes/2023-package#3]
Hello Arjan, 

I am trying to build a custom python package and to learn i started with this repo and your youtube tutorial.
But, after uploaded to testpypi i got this error while trying to install the library:
"""
ERROR: Could not find a version that satisfies the requirement bson>=0.5.10 (from idgenerator-apann) (from versions: 0.5.9)
ERROR: No matching distribution found for bson>=0.5.10
"""

Do you have any suggestion on how to fix it?

This is the link to the uploaded package: https://test.pypi.org/project/idgenerator-apann/

**Comment by dpolimeni** [comment]
Probably solved, it is related to the fact that testpypi is updated up to bson version0 0.5.9 so it does not find it when installing the package from testpypi repo

**Comment by egges** [comment]
Thanks for posting the update. I'll close this issue for the time being.
